name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          check-path: './actions_test'

      - name: Install dependencies
        run: |
          cd ./actions_test
          npm install
      - name: Run lint
        run: |
          cd ./actions_test
          npm run lint
      - name: Run tests
        run: |
          cd ./actions_test
          npm run test
